#!/usr/bin/env python3
"""
Generate assets/i18n.js from i18n/runtime.json.

Strings that live in JavaScript cannot be swapped at build time the way page
copy can, because the markup that carries them does not exist until the script
runs. They ship as one small table instead, and QD.t() picks the row for
whatever <html lang> says.

All three languages travel together. The file is a couple of kilobytes and
splitting it per locale would mean a second request on a page that already
knows its language, which is a worse trade than the bytes.

  python3 tools/i18n/runtime.py
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

data = json.load(open(os.path.join(ROOT, 'i18n', 'runtime.json'), encoding='utf-8'))
data.pop('_readme', None)

table = {'fr': {}, 'es': {}}
for english, per_locale in data.items():
    for code in table:
        value = per_locale.get(code)
        if value:
            table[code][english] = value

body = json.dumps(table, ensure_ascii=False, separators=(',', ':'), sort_keys=True)

js = '''/* Generated by tools/i18n/runtime.py from i18n/runtime.json. Do not edit. */
window.QD = window.QD || {};
(function () {
  'use strict';
  var TABLE = %s;

  /* Resolved once. The language of a page is fixed at build time, so re-reading
     the attribute per lookup would be work with no possible change in answer. */
  var lang = (document.documentElement.getAttribute('lang') || 'en').slice(0, 2);
  var dict = TABLE[lang] || null;

  /* Falls back to the English it was given. A missing translation should show
     the real sentence, not a key or a blank. */
  window.QD.t = function (english) {
    return (dict && dict[english]) || english;
  };
}());
''' % body

with open(os.path.join(ROOT, 'assets', 'i18n.js'), 'w', encoding='utf-8') as fh:
    fh.write(js)

print(f'  assets/i18n.js: {len(data)} strings x {len(table)} languages, {len(js)} bytes')
