#!/usr/bin/env python3
"""
Rebuild sitemap.xml so every page appears once per language, and every entry
cross-references the other two.

Google treats hreflang as a set of claims that must agree: if /fr/about/ says
its English twin is /about/, then /about/ has to say the same back, or the
whole cluster is discarded and one arbitrary language gets indexed. Generating
all three from one list is the only way to keep that true by construction.

  python3 tools/i18n/sitemap.py
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from build import LOCALES, SITE, page_url
from extract import PAGES, ROOT

# lastmod comes from git, so it tracks real edits instead of a hand-bumped
# constant that was already stale within hours (audit finding). changefreq and
# priority are gone: Google ignores both, and emitting them only added noise.
import subprocess

def git_lastmod(path):
    """Last commit date for a file, YYYY-MM-DD. Falls back to today for a
       file that exists but is not yet committed."""
    try:
        out = subprocess.run(
            ['git', 'log', '-1', '--format=%cs', '--', path],
            cwd=ROOT, capture_output=True, text=True, timeout=10)
        d = out.stdout.strip()
        if re.fullmatch(r'\d{4}-\d{2}-\d{2}', d):
            return d
    except Exception:
        pass
    import datetime
    return datetime.date.today().isoformat()


# Standalone files that have no translated twin. The two "-sample" demo PDFs
# were removed: nothing links to them, they are placeholders, and a sitemap
# should not invite the index to disconnected demo files (audit finding).
EXTRA = [
    'https://quentindupard.com/assets/docs/engagement-one-pager.pdf',
]

SKIP = {'404.html'}          # never in a sitemap

# Noindexed pages contradict the sitemap by definition (Search Console flags
# "Submitted URL marked noindex"). /stats/ is deliberately noindexed.
NOINDEX = {'stats/index.html'}


def main():
    rows = []
    for page in PAGES:
        if page in SKIP or page in NOINDEX or not os.path.exists(os.path.join(ROOT, page)):
            continue
        lastmod = git_lastmod(page)

        alternates = [
            f'    <xhtml:link rel="alternate" hreflang="{LOCALES[c]["html"]}" href="{page_url(c, page)}"/>'
            for c in LOCALES
        ]
        alternates.append(
            f'    <xhtml:link rel="alternate" hreflang="x-default" href="{page_url("en", page)}"/>')

        # One <url> per language, each carrying the full reciprocal set.
        for code in LOCALES:
            rows.append('\n'.join([
                '  <url>',
                f'    <loc>{page_url(code, page)}</loc>',
                *alternates,
                f'    <lastmod>{lastmod}</lastmod>',
                '  </url>',
            ]))

    for loc in EXTRA:
        rel = loc.replace(SITE + '/', '')
        lastmod = git_lastmod(rel)
        rows.append('\n'.join([
            '  <url>',
            f'    <loc>{loc}</loc>',
            f'    <lastmod>{lastmod}</lastmod>',
            '  </url>',
        ]))

    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by tools/i18n/sitemap.py. Edit that, not this. -->\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n\n'
        + '\n\n'.join(rows) +
        '\n\n</urlset>\n'
    )
    with open(os.path.join(ROOT, 'sitemap.xml'), 'w', encoding='utf-8') as fh:
        fh.write(xml)

    pages = len([p for p in PAGES if p not in SKIP and p not in NOINDEX])
    print(f'  sitemap.xml: {pages} pages x {len(LOCALES)} languages = '
          f'{pages * len(LOCALES)} URLs, plus {len(EXTRA)} files')


if __name__ == '__main__':
    main()
