#!/usr/bin/env python3
"""
Rebuild sitemap.xml so every page appears once per language, and every entry
cross-references the other two.

Google treats hreflang as a set of claims that must agree: if /fr/about/ says
its English twin is /about/, then /about/ has to say the same back, or the
whole cluster is discarded and one arbitrary language gets indexed. Generating
all three from one list is the only way to keep that true by construction.

  python3 tools/i18n/sitemap.py
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from build import LOCALES, SITE, page_url
from extract import PAGES, ROOT

# lastmod / changefreq / priority carried over from the hand-written sitemap.
# Anything not listed keeps the default row.
DEFAULTS = ('2026-08-27', 'monthly', '0.6')
PAGE_META = {
    'index.html':                            ('2026-08-27', 'monthly', '1.0'),
    'about/index.html':                      ('2026-08-27', 'monthly', '0.8'),
    'research/index.html':                   ('2026-08-27', 'weekly',  '0.8'),
    'privacy/index.html':                    ('2026-08-27', 'yearly',  '0.3'),
    'stats/index.html':                      ('2026-08-27', 'daily',   '0.4'),
}
ARTICLE_META = ('2026-08-27', 'monthly', '0.7')

# Standalone files that have no translated twin.
EXTRA = [
    ('https://quentindupard.com/assets/docs/pricing-teardown-sample.pdf', '2026-08-25', 'yearly', '0.4'),
    ('https://quentindupard.com/assets/docs/activation-audit-sample.pdf', '2026-08-25', 'yearly', '0.4'),
    ('https://quentindupard.com/assets/docs/engagement-one-pager.pdf',    '2026-08-25', 'yearly', '0.4'),
]

SKIP = {'404.html'}          # never in a sitemap


def meta_for(page):
    if page in PAGE_META:
        return PAGE_META[page]
    if page.startswith('research/') and page != 'research/index.html':
        return ARTICLE_META
    return DEFAULTS


def main():
    rows = []
    for page in PAGES:
        if page in SKIP or not os.path.exists(os.path.join(ROOT, page)):
            continue
        lastmod, freq, priority = meta_for(page)

        alternates = [
            f'    <xhtml:link rel="alternate" hreflang="{LOCALES[c]["html"]}" href="{page_url(c, page)}"/>'
            for c in LOCALES
        ]
        alternates.append(
            f'    <xhtml:link rel="alternate" hreflang="x-default" href="{page_url("en", page)}"/>')

        # One <url> per language, each carrying the full reciprocal set.
        for code in LOCALES:
            rows.append('\n'.join([
                '  <url>',
                f'    <loc>{page_url(code, page)}</loc>',
                *alternates,
                f'    <lastmod>{lastmod}</lastmod>',
                f'    <changefreq>{freq}</changefreq>',
                f'    <priority>{priority}</priority>',
                '  </url>',
            ]))

    for loc, lastmod, freq, priority in EXTRA:
        rows.append('\n'.join([
            '  <url>',
            f'    <loc>{loc}</loc>',
            f'    <lastmod>{lastmod}</lastmod>',
            f'    <changefreq>{freq}</changefreq>',
            f'    <priority>{priority}</priority>',
            '  </url>',
        ]))

    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by tools/i18n/sitemap.py. Edit that, not this. -->\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n\n'
        + '\n\n'.join(rows) +
        '\n\n</urlset>\n'
    )
    with open(os.path.join(ROOT, 'sitemap.xml'), 'w', encoding='utf-8') as fh:
        fh.write(xml)

    pages = len([p for p in PAGES if p not in SKIP])
    print(f'  sitemap.xml: {pages} pages x {len(LOCALES)} languages = '
          f'{pages * len(LOCALES)} URLs, plus {len(EXTRA)} files')


if __name__ == '__main__':
    main()
