#!/usr/bin/env python3
"""
Inline the render-blocking CSS.

  python3 tools/critical.py

Every page used to block first paint on three stylesheet requests. This
tool rewrites the English pages so that:

  - glass.css and site.css (the shared chrome) are inlined in full on
    every page, and their <link> tags are removed;
  - article.css / stats.css are inlined in full on the pages that use
    them, since they are small and mostly above the fold there;
  - home.css (the big one) stays external on the homepage but loads
    without blocking (media="print" + onload swap, noscript fallback),
    with only its /* critical:start */../* critical:end */ sections
    inlined so the hero and ask surface never flash unstyled.

The result: zero render-blocking stylesheets. Edit the CSS files, never
the inlined copy — then re-run this (tools/i18n/build.py calls it), and
the i18n build carries the head into fr/ and es/.
"""
import glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

START = '<!-- inline:critical — generated by tools/critical.py; edit assets/*.css, not this -->'
END = '<!-- /inline:critical -->'

def minify(css):
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    css = re.sub(r'\s+', ' ', css)
    css = re.sub(r'\s*([{}:;,>])\s*', r'\1', css)
    return css.replace(';}', '}').strip()

def marked(css):
    return '\n'.join(re.findall(r'/\* critical:start[^*]*\*/(.*?)/\* critical:end \*/', css, re.S))

def read(name):
    return open(os.path.join(ROOT, 'assets', name), encoding='utf-8').read()

def process(path):
    s = open(path, encoding='utf-8').read()
    # Restore any previous run: drop the inline block, put plain links back.
    s = re.sub(re.escape(START) + r'.*?' + re.escape(END) + r'\n?', '', s, flags=re.S)
    s = re.sub(r'<link rel="stylesheet" href="(/assets/[a-z]+\.css\?v=\d+)" media="print"[^>]*>\n?'
               r'(?:<noscript><link rel="stylesheet" href="\1"></noscript>\n?)?',
               lambda m: f'<link rel="stylesheet" href="{m.group(1)}">\n', s)

    links = re.findall(r'<link rel="stylesheet" href="/assets/([a-z]+)\.css\?v=(\d+)">\n?', s)
    sheets = {name: v for name, v in links}
    if 'glass' not in sheets:
        return None

    parts = [minify(read('glass.css')), minify(read('site.css'))]
    keep_async = None
    for name in ('article', 'stats', 'home'):
        if name not in sheets:
            continue
        if name == 'home':
            parts.append(minify(marked(read('home.css'))))
            keep_async = f'/assets/home.css?v={sheets["home"]}'
        else:
            parts.append(minify(read(f'{name}.css')))

    inline = START + '\n<style>' + '\n'.join(p for p in parts if p) + '</style>\n' + END + '\n'

    # Replace the first stylesheet link with the inline block; delete the rest.
    def repl(m):
        name = m.group(1)
        if keep_async and name == 'home':
            return (f'<link rel="stylesheet" href="{keep_async}" media="print" onload="this.media=\'all\'">\n'
                    f'<noscript><link rel="stylesheet" href="{keep_async}"></noscript>\n')
        return ''
    first = re.search(r'<link rel="stylesheet" href="/assets/[a-z]+\.css\?v=\d+">\n?', s)
    s = s[:first.start()] + inline + s[first.start():]
    s = re.sub(r'<link rel="stylesheet" href="/assets/([a-z]+)\.css\?v=\d+">\n?', repl, s)
    open(path, 'w', encoding='utf-8').write(s)
    return sorted(sheets)

def main():
    pages = (['index.html', '404.html', 'about/index.html', 'privacy/index.html',
              'stats/index.html', 'research/index.html']
             + glob.glob(os.path.join(ROOT, 'research', '*', 'index.html')))
    for p in sorted(set(os.path.join(ROOT, x) if not os.path.isabs(x) else x for x in pages)):
        done = process(p)
        if done:
            print(f'  {os.path.relpath(p, ROOT)}: inlined {"+".join(done)}')

if __name__ == '__main__':
    main()
