#!/usr/bin/env python3
"""
Inline the render-blocking CSS.

  python3 tools/critical.py

Every page used to block first paint on three stylesheet requests. This
tool rewrites the English pages so that:

  - glass.css and site.css (the shared chrome) are inlined in full on
    every page, and their <link> tags are removed;
  - article.css / stats.css are inlined in full on the pages that use
    them, since they are small and mostly above the fold there;
  - home.css (the big one) stays external on the homepage but loads
    without blocking (media="print" + onload swap, noscript fallback),
    with only its /* critical:start */../* critical:end */ sections
    inlined so the hero and ask surface never flash unstyled.

The result: zero render-blocking stylesheets. Edit the CSS files, never
the inlined copy — then re-run this (tools/i18n/build.py calls it), and
the i18n build carries the head into fr/ and es/.
"""
import glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

START = '<!-- inline:critical — generated by tools/critical.py; edit assets/*.css, not this -->'
END = '<!-- /inline:critical -->'

def minify(css):
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    css = re.sub(r'\s+', ' ', css)
    css = re.sub(r'\s*([{}:;,>])\s*', r'\1', css)
    return css.replace(';}', '}').strip()

def read(name):
    return open(os.path.join(ROOT, 'assets', name), encoding='utf-8').read()


def css_chunks(css):
    """Top-level chunks: comments, at-rules with bodies, plain rules."""
    out, i, n = [], 0, len(css)
    while i < n:
        if css.startswith('/*', i):
            j = css.find('*/', i) + 2; i = j; continue
        if css[i] in ' \t\n\r': i += 1; continue
        j = css.find('{', i)
        if j == -1: break
        depth, k = 1, j + 1
        while k < n and depth:
            if css[k] == '{': depth += 1
            elif css[k] == '}': depth -= 1
            k += 1
        out.append((css[i:j].strip(), css[j+1:k-1], css[i:k]))
        i = k
    return out


def home_critical():
    """Every home.css rule whose selector touches a class that appears
       above the fold (nav + hero + the first act), media blocks included.
       Derived from the markup on every run, so new above-fold elements
       pull their styles in automatically."""
    page = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
    cut = page.find('<!-- ══ ACT 02')
    fold = page[:cut if cut > 0 else len(page)]
    toks = set()
    for m in re.findall(r'class="([^"]+)"', fold):
        toks.update(m.split())
    css = read('home.css')
    sel_cls = re.compile(r'\.([\w-]+)')

    def wanted(selector):
        cls = set(sel_cls.findall(selector))
        return bool(cls & toks) if cls else True

    keep = []
    for head, body, full in css_chunks(css):
        if head.startswith('@keyframes') or head.startswith('@-webkit-keyframes'):
            keep.append(full)      # tiny, and animations must not restyle late
        elif head.startswith('@'):
            inner = [f for h, b, f in css_chunks(body) if wanted(h)]
            if inner:
                keep.append(head + '{' + ''.join(inner) + '}')
        elif any(wanted(x) for x in head.split(',')):
            keep.append(full)
    return '\n'.join(keep)


def process(path):
    s = open(path, encoding='utf-8').read()
    rel = os.path.relpath(path, ROOT)

    # Which sheets this page type uses. Derived from the path, not from the
    # <link> tags: the first run removes those, and a re-run that depended
    # on them silently refreshed nothing (the bug this rewrite fixes).
    if rel == 'index.html':
        inline, home_async = ['glass', 'site'], True
    elif rel == 'stats/index.html':
        inline, home_async = ['glass', 'site', 'stats'], False
    else:
        inline, home_async = ['glass', 'site', 'article'], False

    # Read the home.css version BEFORE stripping: the async link that
    # carries it lives inside the generated block.
    home_v = None
    m = re.search(r'href="/assets/home\.css\?v=(\d+)"', s)
    if m: home_v = m.group(1)

    # Drop any previous inline block and any leftover plain links.
    s = re.sub(re.escape(START) + r'.*?' + re.escape(END) + r'\n?', '', s, flags=re.S)
    s = re.sub(r'<link rel="stylesheet" href="/assets/(?:glass|site|article|stats|home)\.css\?v=\d+"[^>]*>\n?'
               r'(?:<noscript><link rel="stylesheet" href="/assets/home\.css\?v=\d+"></noscript>\n?)?', '', s)

    parts = [minify(read(f'{name}.css')) for name in inline]
    links = ''
    if home_async:
        assert home_v, f'{rel}: no home.css version found'
        parts.append(minify(home_critical()))
        href = f'/assets/home.css?v={home_v}'
        links = (f'<link rel="stylesheet" href="{href}" media="print" onload="this.media=\'all\'">\n'
                 f'<noscript><link rel="stylesheet" href="{href}"></noscript>\n')

    block = (START + '\n<style>' + '\n'.join(p for p in parts if p) + '</style>\n'
             + links + END + '\n')

    anchor = "<script>document.documentElement.classList.remove('no-js');</script>"
    assert anchor in s, f'{rel}: no-js anchor missing'
    s = s.replace(anchor, block + anchor, 1)
    open(path, 'w', encoding='utf-8').write(s)
    return inline + (['home-critical'] if home_async else [])


def main():
    pages = (['index.html', '404.html', 'about/index.html', 'privacy/index.html',
              'stats/index.html', 'research/index.html']
             + glob.glob(os.path.join(ROOT, 'research', '*', 'index.html')))
    for p in sorted(set(os.path.join(ROOT, x) if not os.path.isabs(x) else x for x in pages)):
        done = process(p)
        if done:
            print(f'  {os.path.relpath(p, ROOT)}: inlined {"+".join(done)}')

if __name__ == '__main__':
    main()
